config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  get 'signup', to: 'users#new', as: 'signup'
  post 'signup', to: 'users#create'
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  get "up" => "rails/health#show", as: :rails_health_check

  get "user/new"

  namespace :admin do
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
  
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, length: { minimum: 6 }, if: -> { new_record? || !password.nil? }
   def admin?
      admin
   end

  end
  

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.all
  end
  def show
  end

  def edit_user
    @user = User.find(params[:id])
  end
  
  def update_user
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_index_path, notice: 'Usuario actualizado exitosamente.'
    else
      render :edit_user
   end
  end 

   def destroy_user
    user = User.find(params[:id])
    user.destroy
    redirect_to admin_index_path, notice: 'Usuario eliminado exitosamente.'
   end

   def make_admin
    user = User.find(params[:id])
    user.update(admin: true)
    redirect_to admin_index_path, notice: 'Usuario ahora es un administrador.'
  end

  private

  def authenticate_admin!
    unless current_user && current_user.admin?
      redirect_to root_path, alert: 'Acceso no autorizado.'
    end
  end
  def user_params
    params.require(:user).permit(:email, :admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     helper_method :current_user
      
        private
      
        def current_user
          @current_user ||= User.find(session[:user_id]) if session[:user_id]
        end
      

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
      user = User.find_by(email: params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_path, notice: '¡Inicio de sesión exitoso!'
      else
        flash.now[:alert] = 'Email o contraseña incorrectos'
        render :new
      end
    end
  
    def destroy
      session[:user_id] = nil
      redirect_to root_path, notice: '¡Cierre de sesión exitoso!'
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
   end

   def create
        @user = User.new(user_params)
        if @user.save
           session[:user_id] = @user.id
           redirect_to root_path, notice: 'User was successfully created'
        else
           render :new
        end
   end


   private

   def user_params
     params.require(:user).permit(:name, :email, :password, :password_confirmation)
   end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/edit_user.html.erb
<h1>Editar Usuario</h1>

<%= form_with(model: @user, url: update_user_admin_index_path(@user), method: :patch, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :admin %>
    <%= form.check_box :admin %>
  </div>

  <%= form.submit 'Actualizar Usuario', class: 'btn btn-primary' %>
<% end %>

app/views/admin/index.html.erb
<h1>Panel de Administración</h1>

<h2>Listado de Usuarios</h2>
<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.email %> |
      <%= link_to 'Editar', edit_user_admin_index_path(user) %> |
      <%= link_to 'Eliminar', destroy_user_admin_index_path(user), method: :delete, data: { confirm: '¿Estás seguro?' } %>

      <% if user.admin? %>
        (Administrador)
      <% else %>
        <%= link_to 'Hacer Administrador', make_admin_admin_index_path(user), method: :patch, data: { confirm: '¿Hacer administrador?' } %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/home/index.html.erb
<h1>Home</h1>

<% if session[:user_id] %>
  <p>¡Hola, <%= current_user.email %>! Estás logueado.</p>
  <%= link_to "Desconectar", logout_path, method: :delete, class: "btn btn-danger" %>
<% else %>
  <p>No has iniciado sesión.</p>
  <%= link_to "Iniciar sesión", login_path, class: "btn btn-primary" %>
  <%= link_to "Crear cuenta", signup_path, class: "btn btn-success" %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to "Inicio", root_path, class: "nav-link" %>
      </li>
      <% if session[:user_id] %>
        <!-- Si hay una sesión activa, muestra el botón de cerrar sesión -->
        <li class="nav-item">
          <%= link_to "Cerrar sesión", logout_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <!-- Si no hay una sesión activa, muestra los botones de iniciar sesión y crear cuenta -->
        <li class="nav-item">
          <%= link_to "Iniciar sesión", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Crear cuenta", signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portalplacas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

 <body>

  <%= render 'layouts/header' %>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/users/new.html.erb
<h1>Crear Cuenta</h1>

<%= form_with(model: @user, url: signup_path, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= form.submit 'Crear Cuenta', class: 'btn btn-success' %>
<% end %>

<%= link_to '¿Ya tienes una cuenta? Inicia sesión aquí', login_path %>